name: Sync PostgreSQL Database

on:
  push:
    branches:
      - main

jobs:
  sync_db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install paramiko

    - name: Run database sync script
      run: |
        python db_sync.py
      env:
        FIRST_EC2_IP: ${{ secrets.FIRST_EC2_IP }}
        SECOND_EC2_IP: ${{ secrets.SECOND_EC2_IP }}
        SSH_KEY_PATH: ${{ secrets.SSH_KEY_PATH }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        DB_NAME: ${{ secrets.DB_NAME }}
