name: Yedekleme ve Geri Yükleme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Yedekleme ve geri yükleme betiğini çalıştır
        run: |
          # Özel anahtarı bir dosyaya yaz
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem  # Anahtar dosyasının izinlerini güvenli hale getir

          # Python betiğini çalıştır
          python backup_restore.py
        env:
          SOURCE_HOST: ${{ secrets.SOURCE_HOST }}
          DEST_HOST: ${{ secrets.DEST_HOST }}
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}  # GitHub Secret'ı burada kullanılıyor
