name: Sync PostgreSQL Database

on:
  push:
    branches:
      - main

jobs:
  sync_db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        pip install paramiko

    - name: Set up SSH key for EC2 connection
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/public-key.pem
        chmod 600 ~/.ssh/public-key.pem
    
    - name: Run database sync script
      run: |
        python db_sync.py
      env:
        FIRST_EC2_IP: ${{ secrets.FIRST_EC2_IP }}
        SECOND_EC2_IP: ${{ secrets.SECOND_EC2_IP }}
        SSH_KEY_PATH: ~/.ssh/public-key.pem
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
