name: Backup and Restore

on:
  push:
    branches:
      - main

jobs:
  backup-restore:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Create private key file
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > public-key.pem
        chmod 600 public-key.pem  # Set permissions for the private key
    
    - name: Run Python backup and restore script
      run: |
        python backup_restore.py
      env:
        SOURCE_HOST: ${{ secrets.SOURCE_HOST }}
        DEST_HOST: ${{ secrets.DEST_HOST }}
        EC2_PRIVATE_KEY: public-key.pem  # Referencing the private key you uploaded to GitHub Secrets
