name: Backup and Restore PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  backup-restore:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install paramiko

    - name: Run backup and restore script
      env:
        SOURCE_HOST: ${{ secrets.SOURCE_HOST }}
        DEST_HOST: ${{ secrets.DEST_HOST }}
        KEY_FILE_PATH: ${{ secrets.KEY_FILE_PATH }}
      run: |
        python backup_restore.py
